### ISSUE TITLE
MultiModel.load_models fails on Windows

### ISSUE THREAD

**Issue by eefm1** [NREL/polyID#7]
When trying to load a MultiModel on Windows, a FileNotFoundError is raised:

Traceback (most recent call last):
  File "C:\xxx\evaluate_model_performance_and_DoV.py", line 23, in <module>
    mm = MultiModel.load_models("biobased_test")
  File "C:\xxx\polyid\polyid.py", line 541, in load_models
    SingleModel.load_model(
  File "C:\xxx\polyid\polyid.py", line 192, in load_model
    with open(data_fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'xx_test\\model_0\\xx_test\\model_0_data.pk'

This issue is resolved by PR #8

**Comment by jlaw9** [comment]
Thanks for the PR @eefm1 . Looks good. I'll merge it soon.
